version: '3'

services:
  glitchtip:
    image: glitchtip/glitchtip
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgres://glitchtip:glitchtip@postgres:5432/glitchtip
      - REDIS_URL=redis://redis:6379/0
      - DEFAULT_FROM_EMAIL=webmaster@localhost
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - SECRET_KEY=change_this_to_something_very_secret
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=glitchtip
      - POSTGRES_PASSWORD=glitchtip
      - POSTGRES_DB=glitchtip

  redis:
    image: redis:7
